// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using meow.Models;

#nullable disable

namespace meow.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("meow.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Cena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CenaOkladkowa")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("DataPremiery")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataWydania")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EAN")
                        .HasColumnType("longtext");

                    b.Property<string>("Gatunek")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("GlebokoscMm")
                        .HasColumnType("int");

                    b.Property<string>("GpsrCertyfikaty")
                        .HasColumnType("longtext");

                    b.Property<int>("IloscDoSprzedazy")
                        .HasColumnType("int");

                    b.Property<int>("IloscEgzemplarzy")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Indeks")
                        .HasColumnType("longtext");

                    b.Property<string>("JezykOryginalu")
                        .HasColumnType("longtext");

                    b.Property<string>("JezykWydania")
                        .HasColumnType("longtext");

                    b.Property<int?>("LiczbaStron")
                        .HasColumnType("int");

                    b.Property<string>("NumerWydania")
                        .HasColumnType("longtext");

                    b.Property<string>("OkladkaTyp")
                        .HasColumnType("longtext");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<int>("RokWydania")
                        .HasColumnType("int");

                    b.Property<string>("Seria")
                        .HasColumnType("longtext");

                    b.Property<int?>("SzerokoscMm")
                        .HasColumnType("int");

                    b.Property<string>("Tlumaczenie")
                        .HasColumnType("longtext");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TytulOryginalny")
                        .HasColumnType("longtext");

                    b.Property<string>("Wydawnictwo")
                        .HasColumnType("longtext");

                    b.Property<int?>("WysokoscMm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("meow.Models.Egzemplarz", b =>
                {
                    b.Property<int>("IdEgzemplarza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEgzemplarza"));

                    b.Property<int>("IdKsiazka")
                        .HasColumnType("int");

                    b.Property<string>("NumerInwentarzowy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Stan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdEgzemplarza");

                    b.HasIndex("IdKsiazka");

                    b.ToTable("Egzemplarze");
                });

            modelBuilder.Entity("meow.Models.Klient", b =>
                {
                    b.Property<int>("IdKlienta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdKlienta"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdKlienta");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("meow.Models.Platnosc", b =>
                {
                    b.Property<int>("IdPlatnosc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlatnosc"));

                    b.Property<int>("IdWypozyczenie")
                        .HasColumnType("int");

                    b.Property<decimal>("Kwota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPlatnosc");

                    b.HasIndex("IdWypozyczenie")
                        .IsUnique();

                    b.ToTable("Platnosci");
                });

            modelBuilder.Entity("meow.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("KlientId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("meow.Models.Wypozyczenie", b =>
                {
                    b.Property<int>("IdWypozyczenie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdWypozyczenie"));

                    b.Property<DateTime>("DataPlanowanegoZwrotu")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataWypozyczenia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataZwrotu")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdEgzemplarz")
                        .HasColumnType("int");

                    b.Property<int>("IdKlient")
                        .HasColumnType("int");

                    b.Property<int?>("IdKsiazki")
                        .HasColumnType("int");

                    b.HasKey("IdWypozyczenie");

                    b.HasIndex("IdEgzemplarz");

                    b.HasIndex("IdKlient");

                    b.HasIndex("IdKsiazki");

                    b.ToTable("Wypozyczenia");
                });

            modelBuilder.Entity("meow.Models.Zamowienie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataZamowienia")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdKlienta")
                        .HasColumnType("int");

                    b.Property<int?>("IdKsiazki")
                        .HasColumnType("int");

                    b.Property<string>("NumerSledzenia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdKlienta");

                    b.HasIndex("IdKsiazki");

                    b.ToTable("Zamowienia");
                });

            modelBuilder.Entity("meow.Models.Egzemplarz", b =>
                {
                    b.HasOne("meow.Models.Book", "Book")
                        .WithMany("Egzemplarze")
                        .HasForeignKey("IdKsiazka")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("meow.Models.Platnosc", b =>
                {
                    b.HasOne("meow.Models.Wypozyczenie", "Wypozyczenie")
                        .WithOne("Platnosc")
                        .HasForeignKey("meow.Models.Platnosc", "IdWypozyczenie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wypozyczenie");
                });

            modelBuilder.Entity("meow.Models.User", b =>
                {
                    b.HasOne("meow.Models.Klient", "Klient")
                        .WithMany()
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Klient");
                });

            modelBuilder.Entity("meow.Models.Wypozyczenie", b =>
                {
                    b.HasOne("meow.Models.Egzemplarz", "Egzemplarz")
                        .WithMany()
                        .HasForeignKey("IdEgzemplarz");

                    b.HasOne("meow.Models.Klient", "Klient")
                        .WithMany()
                        .HasForeignKey("IdKlient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("meow.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("IdKsiazki")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Book");

                    b.Navigation("Egzemplarz");

                    b.Navigation("Klient");
                });

            modelBuilder.Entity("meow.Models.Zamowienie", b =>
                {
                    b.HasOne("meow.Models.Klient", "Klient")
                        .WithMany()
                        .HasForeignKey("IdKlienta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("meow.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("IdKsiazki");

                    b.Navigation("Book");

                    b.Navigation("Klient");
                });

            modelBuilder.Entity("meow.Models.Book", b =>
                {
                    b.Navigation("Egzemplarze");
                });

            modelBuilder.Entity("meow.Models.Wypozyczenie", b =>
                {
                    b.Navigation("Platnosc");
                });
#pragma warning restore 612, 618
        }
    }
}
